/simulated_reservoir_node:
  ros__parameters:
    # Reservoir selection
    reservoir_type: "double_pendulum"
    
    # Nested reservoir-specific parameters
    reservoir_parameters:
        xml_file: "simulated_double_pendulum.xml"
        dt_ctrl: 0.01
        mujoco_substeps: 10
        rbf_gamma: 0.1
        rbf_components: 100
        ctrl_scale: 1.0
        leak_rate: 0.3
        seed: 42
        warmup_steps: 30
      